-- Our Space — Supabase schema. Run in a fresh project SQL editor.
create extension if not exists pgcrypto;
create type public.feeling_kind as enum ('gratitude','disappointment');
create type public.reaction_kind as enum ('understood','talk_together','sorry','thank_you');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null check(char_length(display_name) between 1 and 40), avatar_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.couples (id uuid primary key default gen_random_uuid(), title text not null default '우리 둘의 공간', relationship_started_on date, invite_code text unique, invite_expires_at timestamptz, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.couple_members (couple_id uuid not null references public.couples(id) on delete cascade, user_id uuid not null unique references public.profiles(id) on delete cascade, joined_at timestamptz not null default now(), primary key(couple_id,user_id));
create table public.daily_statuses (id uuid primary key default gen_random_uuid(), couple_id uuid not null references public.couples(id) on delete cascade, user_id uuid not null references public.profiles(id), status_date date not null default current_date, mood text not null, energy smallint not null check(energy between 0 and 100), miss_you smallint not null check(miss_you between 0 and 100), food text, activity text, memo text check(char_length(memo)<=500), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,status_date));
create table public.feelings_posts (id uuid primary key default gen_random_uuid(), couple_id uuid not null references public.couples(id) on delete cascade, author_id uuid not null references public.profiles(id), kind public.feeling_kind not null, situation text not null, feeling text, request text, urgent boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.feeling_reads (post_id uuid not null references public.feelings_posts(id) on delete cascade, user_id uuid not null references public.profiles(id), read_at timestamptz not null default now(), primary key(post_id,user_id));
create table public.feeling_reactions (post_id uuid not null references public.feelings_posts(id) on delete cascade, user_id uuid not null references public.profiles(id), reaction public.reaction_kind not null, created_at timestamptz not null default now(), primary key(post_id,user_id,reaction));
create table public.daily_questions (id uuid primary key default gen_random_uuid(), couple_id uuid references public.couples(id) on delete cascade, question_date date not null, prompt text not null check(char_length(prompt) between 1 and 300), created_by uuid references public.profiles(id), created_at timestamptz not null default now(), unique(couple_id,question_date));
create table public.daily_answers (id uuid primary key default gen_random_uuid(), question_id uuid not null references public.daily_questions(id) on delete cascade, user_id uuid not null references public.profiles(id), answer text not null check(char_length(answer) between 1 and 2000), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(question_id,user_id));
create table public.loving_notes (id uuid primary key default gen_random_uuid(), couple_id uuid not null references public.couples(id) on delete cascade, author_id uuid not null references public.profiles(id), body text not null check(char_length(body) between 1 and 1000), created_at timestamptz not null default now());
create table public.memories (id uuid primary key default gen_random_uuid(), couple_id uuid not null references public.couples(id) on delete cascade, author_id uuid not null references public.profiles(id), title text not null, memory_date date not null, description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.memory_photos (id uuid primary key default gen_random_uuid(), memory_id uuid not null references public.memories(id) on delete cascade, storage_path text not null unique, sort_order integer not null default 0, created_at timestamptz not null default now());
create table public.bucket_list_items (id uuid primary key default gen_random_uuid(), couple_id uuid not null references public.couples(id) on delete cascade, created_by uuid not null references public.profiles(id), title text not null check(char_length(title) between 1 and 160), category text, due_date date, completed_at timestamptz, completed_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), couple_id uuid not null references public.couples(id) on delete cascade, recipient_id uuid not null references public.profiles(id), kind text not null, entity_id uuid, read_at timestamptz, created_at timestamptz not null default now());
create index daily_statuses_couple_date_idx on public.daily_statuses(couple_id,status_date desc); create index feelings_couple_created_idx on public.feelings_posts(couple_id,created_at desc); create index memories_couple_date_idx on public.memories(couple_id,memory_date desc); create index bucket_couple_idx on public.bucket_list_items(couple_id,completed_at); create index notifications_unread_idx on public.notifications(recipient_id,created_at desc) where read_at is null;

create or replace function public.is_couple_member(target uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.couple_members where couple_id=target and user_id=auth.uid()) $$;
create or replace function public.generate_invite_code() returns text language plpgsql security definer set search_path=public as $$ declare code text; begin loop code := upper(substr(encode(gen_random_bytes(6),'hex'),1,8)); exit when not exists(select 1 from public.couples where invite_code=code); end loop; return code; end $$;
create or replace function public.join_couple_by_code(code text) returns uuid language plpgsql security definer set search_path=public as $$ declare target uuid; begin if exists(select 1 from public.couple_members where user_id=auth.uid()) then raise exception 'already_paired'; end if; select id into target from public.couples where invite_code=upper(code) and invite_expires_at>now() for update; if target is null then raise exception 'invalid_invite'; end if; if (select count(*) from public.couple_members where couple_id=target)>=2 then raise exception 'couple_full'; end if; insert into public.couple_members(couple_id,user_id) values(target,auth.uid()); update public.couples set invite_code=null,invite_expires_at=null where id=target; return target; end $$;

alter table public.profiles enable row level security; alter table public.couples enable row level security; alter table public.couple_members enable row level security; alter table public.daily_statuses enable row level security; alter table public.feelings_posts enable row level security; alter table public.feeling_reads enable row level security; alter table public.feeling_reactions enable row level security; alter table public.daily_questions enable row level security; alter table public.daily_answers enable row level security; alter table public.loving_notes enable row level security; alter table public.memories enable row level security; alter table public.memory_photos enable row level security; alter table public.bucket_list_items enable row level security; alter table public.notifications enable row level security;
create policy "profile self or partner read" on public.profiles for select using(id=auth.uid() or exists(select 1 from public.couple_members mine join public.couple_members theirs using(couple_id) where mine.user_id=auth.uid() and theirs.user_id=profiles.id)); create policy "profile self write" on public.profiles for all using(id=auth.uid()) with check(id=auth.uid());
create policy "couple members read" on public.couples for select using(public.is_couple_member(id)); create policy "authenticated create couple" on public.couples for insert to authenticated with check(created_by=auth.uid()); create policy "couple creator update" on public.couples for update using(created_by=auth.uid()) with check(public.is_couple_member(id));
create policy "members read membership" on public.couple_members for select using(public.is_couple_member(couple_id)); create policy "user adds self" on public.couple_members for insert with check(user_id=auth.uid());
create policy "members read statuses" on public.daily_statuses for select using(public.is_couple_member(couple_id)); create policy "own status insert" on public.daily_statuses for insert with check(user_id=auth.uid() and public.is_couple_member(couple_id)); create policy "own status update" on public.daily_statuses for update using(user_id=auth.uid()) with check(user_id=auth.uid() and public.is_couple_member(couple_id)); create policy "own status delete" on public.daily_statuses for delete using(user_id=auth.uid());
create policy "members read feelings" on public.feelings_posts for select using(public.is_couple_member(couple_id)); create policy "own feelings write" on public.feelings_posts for insert with check(author_id=auth.uid() and public.is_couple_member(couple_id)); create policy "own feelings update" on public.feelings_posts for update using(author_id=auth.uid()); create policy "own feelings delete" on public.feelings_posts for delete using(author_id=auth.uid());
create policy "member feeling reads" on public.feeling_reads for all using(exists(select 1 from public.feelings_posts p where p.id=post_id and public.is_couple_member(p.couple_id))) with check(user_id=auth.uid() and exists(select 1 from public.feelings_posts p where p.id=post_id and public.is_couple_member(p.couple_id))); create policy "member reactions read" on public.feeling_reactions for select using(exists(select 1 from public.feelings_posts p where p.id=post_id and public.is_couple_member(p.couple_id))); create policy "own reactions write" on public.feeling_reactions for insert with check(user_id=auth.uid() and exists(select 1 from public.feelings_posts p where p.id=post_id and public.is_couple_member(p.couple_id))); create policy "own reactions delete" on public.feeling_reactions for delete using(user_id=auth.uid());
create policy "members read questions" on public.daily_questions for select using(couple_id is null or public.is_couple_member(couple_id)); create policy "members create questions" on public.daily_questions for insert with check(created_by=auth.uid() and public.is_couple_member(couple_id));
-- Answer privacy is enforced through this view/function: clients must not select daily_answers directly.
create policy "own answers only" on public.daily_answers for select using(user_id=auth.uid()); create policy "own answer insert" on public.daily_answers for insert with check(user_id=auth.uid() and exists(select 1 from public.daily_questions q where q.id=question_id and public.is_couple_member(q.couple_id))); create policy "own answer update" on public.daily_answers for update using(user_id=auth.uid());
create or replace function public.revealed_answers(qid uuid) returns setof public.daily_answers language sql stable security definer set search_path=public as $$ select a.* from public.daily_answers a join public.daily_questions q on q.id=a.question_id where a.question_id=qid and public.is_couple_member(q.couple_id) and (select count(distinct user_id) from public.daily_answers where question_id=qid)=2 $$;
create policy "members notes read" on public.loving_notes for select using(public.is_couple_member(couple_id)); create policy "own notes insert" on public.loving_notes for insert with check(author_id=auth.uid() and public.is_couple_member(couple_id)); create policy "own notes delete" on public.loving_notes for delete using(author_id=auth.uid());
create policy "members memories read" on public.memories for select using(public.is_couple_member(couple_id)); create policy "members memories insert" on public.memories for insert with check(author_id=auth.uid() and public.is_couple_member(couple_id)); create policy "own memories update" on public.memories for update using(author_id=auth.uid()); create policy "own memories delete" on public.memories for delete using(author_id=auth.uid());
create policy "members photos read" on public.memory_photos for select using(exists(select 1 from public.memories m where m.id=memory_id and public.is_couple_member(m.couple_id))); create policy "members photos write" on public.memory_photos for insert with check(exists(select 1 from public.memories m where m.id=memory_id and public.is_couple_member(m.couple_id)));
create policy "members bucket read" on public.bucket_list_items for select using(public.is_couple_member(couple_id)); create policy "members bucket insert" on public.bucket_list_items for insert with check(created_by=auth.uid() and public.is_couple_member(couple_id)); create policy "members bucket update" on public.bucket_list_items for update using(public.is_couple_member(couple_id)); create policy "creator bucket delete" on public.bucket_list_items for delete using(created_by=auth.uid());
create policy "own notifications" on public.notifications for select using(recipient_id=auth.uid()); create policy "own notification update" on public.notifications for update using(recipient_id=auth.uid());

insert into storage.buckets(id,name,public) values('memory-photos','memory-photos',false) on conflict do nothing;
create policy "couple photo read" on storage.objects for select using(bucket_id='memory-photos' and public.is_couple_member((storage.foldername(name))[1]::uuid)); create policy "couple photo upload" on storage.objects for insert with check(bucket_id='memory-photos' and public.is_couple_member((storage.foldername(name))[1]::uuid) and owner_id=auth.uid()::text); create policy "owner photo delete" on storage.objects for delete using(bucket_id='memory-photos' and owner_id=auth.uid()::text);
