"use client";
import { FormEvent, useState } from "react";

export function Today(){const [saved,setSaved]=useState(false);const [miss,setMiss]=useState(84);const [pick,setPick]=useState("?");return <Feature title="오늘의 우리" eyebrow="DAILY CHECK-IN" desc="말로 설명하기 어려운 하루도, 가볍게 남겨주세요."><div className="two-col"><section className="form-card"><h2>오늘 기분은 어땠나요?</h2><div className="mood-options">{["☀ 평온해요","🌿 기대돼요","☁ 지쳤어요","🌙 생각이 많아요"].map((x,i)=><button className={i===0?"selected":""} key={x}>{x}</button>)}</div><label>에너지 레벨 <input type="range" defaultValue="68"/><span>68%</span></label><label>얼마나 보고 싶나요? <input type="range" value={miss} onChange={e=>setMiss(+e.target.value)}/><span>{miss}%</span></label><label>오늘 먹고 싶은 것<input placeholder="예: 따뜻한 샤브샤브"/></label><label>오늘 같이 하고 싶은 것<input placeholder="예: 한강 따라 걷기"/></label><label>짧은 메모<textarea placeholder="오늘의 마음을 편하게 적어주세요."/></label><button className="button" onClick={()=>setSaved(true)}>{saved?"저장했어요 ✓":"오늘의 상태 저장"}</button></section><aside><section className="picker-card"><span>WHAT TO EAT?</span><h2>오늘 뭐 먹을까요?</h2><div className="picker-result">{pick}</div><p>{pick==="?"?"두 사람의 선택 중 하나를 골라드려요.":"오늘은 이 메뉴 어때요?"}</p><button onClick={()=>setPick(["샤브샤브","냉모밀","마르게리타 피자"][Math.floor(Math.random()*3)])}>메뉴 뽑기 ↻</button></section><section className="mini-status"><b>♥ 2일 연속 기록 중</b><p>연인이 된 첫날부터 매일 기록하고 있어요.</p></section></aside></div></Feature>}

export function Feelings(){const [reaction,setReaction]=useState("");return <Feature title="마음을 나누는 곳" eyebrow="SAFE CONVERSATIONS" desc="누가 맞는지보다, 서로를 더 잘 이해하기 위한 대화예요."><div className="tabs"><button className="active">서운했던 점 <i>1</i></button><button>고마웠던 점</button><button>내가 쓴 마음</button></div><article className="feeling-post"><header><div className="person"><div className="avatar b">다</div><div><b>다연</b><small>오늘 오후 2:18 · 읽지 않음</small></div></div><span className="gentle">급하지 않아요</span></header><div className="safe-grid"><div><small>어떤 일이 있었나요?</small><p>어제 저녁에 내가 이야기할 때 휴대폰을 계속 보고 있어서, 내 말에 집중하지 않는 것처럼 느껴졌어.</p></div><div><small>나는 어떻게 느꼈나요?</small><p>조금 서운하고 혼자 이야기하는 기분이 들었어.</p></div><div><small>다음에는 무엇이 도움이 될까요?</small><p>잠깐만이라도 휴대폰을 내려놓고 눈을 봐주면 좋겠어.</p></div></div><div className="helper">이 마음은 비난이 아니라, 더 가까워지고 싶다는 표현이에요.</div><footer><span>어떤 마음을 전하고 싶나요?</span><div>{["이해했어요","같이 얘기해요","미안해요","고마워요"].map(x=><button key={x} className={reaction===x?"selected":""} onClick={()=>setReaction(x)}>{reaction===x?"✓ ":""}{x}</button>)}</div></footer></article><section className="compose"><div><h2>새로운 마음 남기기</h2><p>관찰한 일과 느낀 마음을 나누어 쓰면 서로 이해하기 쉬워져요.</p></div><button className="button">마음 정리해서 전하기 +</button></section></Feature>}

export function Questions(){const [answered,setAnswered]=useState(false);return <Feature title="오늘의 질문" eyebrow="QUESTION OF THE DAY" desc="같은 질문, 서로 다른 마음. 두 사람의 답이 모이면 함께 열려요."><section className="question-hero"><span>2026. 08. 28 · QUESTION 142</span><h2>우리 둘이 닮았다고 느끼는<br/>순간은 언제인가요?</h2><p>답변은 두 사람 모두 제출한 뒤에 공개돼요.</p></section><div className="answer-grid"><article><div className="person"><div className="avatar a">서</div><b>나의 답변</b></div>{answered?<p className="answer-copy">같은 장면에서 동시에 웃음이 터질 때. 굳이 설명하지 않아도 같은 걸 보고 있다는 느낌이 좋아.</p>:<><textarea placeholder="떠오르는 마음을 솔직하게 적어보세요."/><button className="button" onClick={()=>setAnswered(true)}>답변 제출하기</button></>}</article><article className="locked"><div className="person"><div className="avatar b">다</div><b>다연의 답변</b></div><div className="lock">♙<h3>{answered?"다연님의 답변을 기다리는 중":"아직 잠겨 있어요"}</h3><p>두 사람의 답변이 모두 도착하면 열려요.</p></div></article></div><button className="outline-action">+ 우리만의 질문 추가하기</button></Feature>}

export function Memories(){return <Feature title="우리의 기록" eyebrow="MEMORY ALBUM" desc="평범했던 날도, 함께라서 특별했던 장면으로 남겨요."><div className="toolbar"><div><button className="active">전체</button><button>2026</button><button>2025</button><button>2024</button></div><button className="button">+ 추억 남기기</button></div><div className="timeline"><span className="year">2026</span><Memory date="08. 17" title="비가 와서 더 좋았던 제주" text="계획대로 된 건 하나도 없었지만, 우산 하나를 나눠 쓰며 오래 걸었던 날." color="coral"/><Memory date="05. 18" title="우리의 두 번째 기념일" text="좋아하는 식당에서 천천히 저녁을 먹고, 내년의 우리에게 편지를 썼다." color="lavender"/><Memory date="03. 02" title="봄을 먼저 만난 오후" text="아직 쌀쌀했지만 햇빛만은 완연한 봄이었다." color="butter"/></div></Feature>}
function Memory({date,title,text,color}:{date:string,title:string,text:string,color:string}){return <article className="memory"><div className="date">{date}</div><div className={`memory-image ${color}`}><span>OUR MOMENT</span></div><div><h2>{title}</h2><p>{text}</p><small>서진 · 다연</small></div></article>}

export function Bucket(){const [items,setItems]=useState([{t:"제주 올레길 함께 걷기",c:"여행",done:true},{t:"도자기 원데이 클래스",c:"경험",done:false},{t:"서로의 인생 영화 10편 보기",c:"일상",done:false},{t:"한 달 살기 해보기",c:"꿈",done:false}]);return <Feature title="같이 하고 싶은 것" eyebrow="OUR BUCKET LIST" desc="언젠가를 구체적인 약속으로. 둘의 바람을 하나씩 이뤄가요."><section className="progress-card"><div><strong>12</strong><span>개의 꿈 중 <b>4개</b>를 이뤘어요</span></div><div className="progress"><i style={{width:"33%"}}/></div><p>우리의 다음 장면까지 8개의 설렘이 남았어요.</p></section><div className="toolbar"><div><button className="active">전체 12</button><button>여행</button><button>일상</button><button>새로운 경험</button></div><button className="button">+ 새 목록</button></div><div className="bucket-items">{items.map((x,i)=><article className={x.done?"done":""} key={x.t}><button aria-label="완료 표시" onClick={()=>setItems(items.map((y,j)=>j===i?{...y,done:!y.done}:y))}>{x.done?"✓":""}</button><div><h3>{x.t}</h3><span>{x.c}</span></div><span>•••</span></article>)}</div></Feature>}

export function Settings(){return <Feature title="설정" eyebrow="OUR SPACE" desc="둘만의 공간을 우리답게 관리해요."><div className="settings-grid"><aside><button className="active">우리의 정보</button><button>내 프로필</button><button>알림</button><button>화면 설정</button><button>개인정보와 보안</button></aside><form className="settings-card" onSubmit={(e:FormEvent)=>e.preventDefault()}><h2>우리의 정보</h2><p>두 사람에게 표시되는 공간의 기본 정보예요.</p><label>공간 이름<input defaultValue="서진 & 다연의 공간"/></label><label>연애 시작일<input type="date" defaultValue="2026-08-27"/></label><label>초대 코드<div className="code"><b>OURS-7K2P</b><button type="button">복사</button></div><small>아직 짝을 찾지 않은 경우에만 사용할 수 있어요.</small></label><div className="divider"/><h3>함께하는 사람</h3><div className="partner-row"><div className="avatar b">다</div><div><b>다연</b><small>dayeon@example.com · 연결됨</small></div><span>파트너</span></div><button className="button">변경사항 저장</button></form></div></Feature>}

function Feature({title,eyebrow,desc,children}:{title:string;eyebrow:string;desc:string;children:React.ReactNode}){return <div className="feature-page page-enter"><header className="feature-head"><span>{eyebrow}</span><h1>{title}</h1><p>{desc}</p></header>{children}</div>}
